### ISSUE TITLE
Ubuntu 22.04.2: OLA olad version: 0.10.9:  rdm_test_server.py  -> ModuleNotFoundError: No module named 'ola'

### ISSUE THREAD

**Issue by vanvught** [OpenLightingProject/ola#1858]
Just compiled the latest OLA and having issues with `rdm_test_server.py`

```
~/ola-0.10.9$ rdm_test_server.py 
Traceback (most recent call last):
  File "/usr/local/bin/rdm_test_server.py", line 37, in <module>
    from ola.ClientWrapper import ClientWrapper, SelectServer
ModuleNotFoundError: No module named 'ola'
```

Please advise. Thanks, Arjan

```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy
```
```
 git clone https://github.com/protocolbuffers/protobuf.git
 cd protobuf/
 git checkout v3.12.4
 ./autogen.sh
 ./configure

....


 make -j 8
 sudo make install
```

```
wget https://github.com/OpenLightingProject/ola/releases/download/0.10.9/ola-0.10.9.tar.gz
tar xvf ola-0.10.9.tar.gz 
cd ola-0.10.9/
 ./configure --enable-rdm-tests --disable-uart --enable-python-libs --disable-pathport --disable-renard --disable-sandnet --disable-uartdmx --disable-usbdmx --disable-stageprofi --disable-espnet --disable-ftdidmx --disable-gpio --disable-opendmx --disable-openpixelcontrol --disable-shownet --disable-spi --disable-karate --disable-milinst

OLA Version 0.10.9

Prefix: '/usr/local'
Compiler: 'g++ -g -O2 -std=gnu++11  '
Linker: '/usr/bin/ld -m elf_x86_64   '
Python: /usr/bin/python

Python API: yes
Java API: no
Enable HTTP Server: yes
RDM Responder Tests: yes
Ja Rule: no
Enabled Plugins: artnet dummy e131 kinet usbpro
UUCP Lock Directory: /var/lock

Now type 'make [<target>]'
  where the optional <target> is:
    all          - build everything
    check        - run the tests
    doxygen-doc  - generate the HTML documentation
    lint         - run the linters
-------------------------------------------------------


 make -j 10
 sudo make install
```

```
olad --version
OLA olad version: 0.10.9
```

```
============================================================================
Testsuite summary for OLA 0.10.9
============================================================================
# TOTAL: 91
# PASS:  83
# SKIP:  0
# XFAIL: 0
# FAIL:  8
# XPASS: 0
# ERROR: 0
============================================================================
See ./test-suite.log
Please report to open-lighting@googlegroups.com
============================================================================

```
[test-suite.log](https://github.com/OpenLightingProject/ola/files/11725380/test-suite.log)

**Comment by vanvught** [comment]
Same issue with a fresh install Debian 12.

```
lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm
```


```
apt install cpplint libcppunit-dev uuid-dev pkg-config libncurses5-dev libtool autoconf automake g++ libmicrohttpd-dev libprotobuf-dev libprotoc-dev zlib1g-dev bison flex make libftdi-dev libftdi1 libusb-1.0-0-dev liblo-dev libavahi-client-dev python3-protobuf libprotobuf* protobuf-*

wget https://github.com/OpenLightingProject/ola/releases/download/0.10.9/ola-0.10.9.tar.gz
tar xvf ola-0.10.9.tar.gz 
cd ola-0.10.9/

autoreconf -i

 ./configure --enable-rdm-tests  --enable-python-libs --disable-uart --disable-pathport --disable-renard --disable-sandnet --disable-uartdmx --disable-usbdmx --disable-stageprofi --disable-espnet --disable-ftdidmx --disable-gpio --disable-opendmx --disable-openpixelcontrol --disable-shownet --disable-spi --disable-karate --disable-milinst
```

```
@debian12:~$ rdm_test_server.py 
Traceback (most recent call last):
  File "/usr/local/bin/rdm_test_server.py", line 37, in <module>
    from ola.ClientWrapper import ClientWrapper, SelectServer
ModuleNotFoundError: No module named 'ola'
```

**Comment by vanvught** [comment]
Hi @DaAwesomeP ,

The Python 2 is not available anymore on latest Ubuntu and Debian. 

**Ubuntu 22.04.2**
```
@nuc-i7:~$ python --version
Python 3.10.6
@nuc-i7:~$ python2 --version
Command 'python2' not found, but can be installed with:
sudo apt install python2
@nuc-i7:~$ python3 --version
Python 3.10.6
@nuc-i7:~$ which rdm_test_server.py
/usr/local/bin/rdm_test_server.py
@nuc-i7:~$ python $(which rdm_test_server.py)
Traceback (most recent call last):
  File "/usr/local/bin/rdm_test_server.py", line 37, in <module>
    from ola.ClientWrapper import ClientWrapper, SelectServer
ModuleNotFoundError: No module named 'ola'
```

**Debian12**
```
@debian12:~$ python --version
Python 3.11.2
@debian12:~$ python2 --version
-bash: python2: command not found
@debian12:~$ python3 --version
Python 3.11.2
@debian12:~$ which rdm_test_server.py
/usr/local/bin/rdm_test_server.py
@debian12:~$ python $(which rdm_test_server.py)
Traceback (most recent call last):
  File "/usr/local/bin/rdm_test_server.py", line 37, in <module>
    from ola.ClientWrapper import ClientWrapper, SelectServer
ModuleNotFoundError: No module named 'ola'
```

**Comment by DaAwesomeP** [comment]
> The Python 2 is not available anymore on latest Ubuntu and Debian.

Yes, this is what I suspected. It seems that 10.9 does contain the Python 3 fixes but maybe it isn't installing properly with `make install`.

Can you try the Debian packages that I linked to? While they don't solve the issue you found, they should work because they install differently. These are official builds from this repo.

**Comment by DaAwesomeP** [comment]
@vanvught Amazing! I'm glad that workaround worked for you!

We should leave this open because there seems to be an issue with how `make install` installs the `ola` dependency for Python 3.

**Comment by unitware** [comment]
any news on how to fix this manually or in the install?

**Comment by jensgol** [comment]
I had the same problem with my fresh installed Mint 22.1, ola 0.10.9 and python 3.12 and found out, what the problem with the python scripts is:

there is a problem in the "configure" script around line 23170, where the PYTHON path from the system is detected.
In Mint the ola python packages should be have a target path in '/usr/**local**/lib/python3.12/dist-packages/ola/'.
But if I make
```
./configure --enable-rdm-tests --enable-python-libs
make all
make install
```
the modules are installed in '/usr/**local/local**/lib/python3.12/dist-packages/ola/', so the prefix 'local' is doubled.
In config.log you see also the wrong path:

```
configure:23165: checking for python script directory
configure:23200: result: ${prefix}/local/lib/python3.12/dist-packages
```

This must be fixed in the configure script, but a workaround is to give the (wrong) python path to the scripts:
```
PYTHONPATH=/usr/local/local/lib/python3.12/dist-packages rdm_test_server.py
Checking olad status
Running RDM Tests Server on http://127.0.0.1:9099

```


Jens
