### ISSUE TITLE
macOS: 0.10.9_1 (latest brew upgrade) : ModuleNotFoundError: No module named 'ola.StringUtils': 0.10.9_1 (brew install) : 

### ISSUE THREAD

**Issue by vanvught** [OpenLightingProject/ola#1859]
This might be similar to #1858 

```
[arjanvanvught@MacBook-Air-2 ~]$ rdm_test_server.py 
Traceback (most recent call last):
  File "/usr/local/bin/rdm_test_server.py", line 39, in <module>
    from ola.testing.rdm import (DataLocation, TestDefinitions, TestLogger,
  File "/usr/local/lib/python3.11/site-packages/ola/testing/rdm/TestDefinitions.py", line 32, in <module>
    from ola.StringUtils import StringEscape
```

```
[arjanvanvught@MacBook-Air-2 ~]$ brew info ola 
==> ola: stable 0.10.9 (bottled), HEAD
Open Lighting Architecture for lighting control information
https://www.openlighting.org/ola/
/usr/local/Cellar/ola/0.10.9_1 (462 files, 19MB) *
  Poured from bottle using the formulae.brew.sh API on 2023-06-17 at 18:25:27
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/ola.rb
License: GPL-2.0-or-later and LGPL-2.1-or-later
==> Dependencies
Build: autoconf ✔, automake ✔, libtool ✔, pkg-config ✔
Required: liblo ✔, libmicrohttpd ✔, libusb ✔, numpy ✔, protobuf@21 ✔, python@3.11 ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
To use the bundled Python libraries:
  export PYTHONPATH=/usr/local/opt/protobuf@21/lib/python3.11/site-packages
```

```
[arjanvanvught@MacBook-Air-2 ~]$ sw_vers
ProductName:	macOS
ProductVersion:	12.6.6
BuildVersion:	21G646
```

```
[arjanvanvught@MacBook-Air-2 ~]$ cat .zshrc 
export CLICOLOR=1
export PATH="/usr/local/sbin:$PATH"
export PATH="/usr/local/opt/llvm/bin:$PATH"

source ~/.git-prompt.sh
setopt PROMPT_SUBST ; PS1='[%n@%m %c$(__git_ps1 " (%s)")]\$ '
export PYTHONPATH=/usr/local/opt/protobuf@21/lib/python3.11/site-packages
```

**Comment by peternewman** [comment]
This is just #1835 which we've already fixed and just not released since sorry.
