### ISSUE TITLE
RDM Tests - GetMaxPacketSize or DetermineMaxPacketSize - TypeError: can't concat str to bytes

### ISSUE THREAD

**Issue by marknorton68** [OpenLightingProject/ola#1969]
Error: can't concat str to bytes

Traceback (most recent call last):
  File "/usr/local/bin/rdm_test_server.py", line 283, in _RunTests
    tests, device = runner.RunTests(test_filter, False, self._UpdateStats)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmx/ola/python/ola/testing/rdm/TestRunner.py", line 346, in RunTests
    test.Run()
  File "/home/dmx/ola/python/ola/testing/rdm/ResponderTest.py", line 321, in Run
    super(ResponderTestFixture, self).Run()
  File "/home/dmx/ola/python/ola/testing/rdm/ResponderTest.py", line 249, in Run
    self.Test()
  File "/home/dmx/ola/python/ola/testing/rdm/TestDefinitions.py", line 619, in Test
    data += chr(i)
TypeError: can't concat str to bytes

**Comment by marknorton68** [comment]
DetermineMaxPacket size

**Comment by peternewman** [comment]
Sorry for the slow reply!

Do you mean DetermineMaxPacketSize not GetMaxPacketSize?
https://github.com/OpenLightingProject/ola/blob/b90866cd6742e68fa67e66217ec230cc1282f23e/tools/rdm/TestDefinitions.py#L619

What version of OLA and Python are you using?

**Comment by peternewman** [comment]
As per the auto-closure, this is now fixed in our master branch @marknorton68 . Let us know if you have any further issues with it.
