### ISSUE TITLE
ola_rdm_get.py throws AttributeError when issuing a "get parameter_description"

### ISSUE THREAD

**Issue by rmull** [OpenLightingProject/ola#884]
I am getting a Python (2.7.9) traceback when issuing the following command:
```
./ola_rdm_get.py -u 1 --uid 3638:12000001 parameter_description
```

I get this in interactive mode (-i) as well, which I was using in an attempt to be able to specify the PID of the parameter I wanted described. Here is the traceback text:
```
Traceback (most recent call last):
  File "./ola_rdm_get.py", line 485, in <module>
    main()
  File "./ola_rdm_get.py", line 481, in main
    controller.onecmd('%s %s' % (request_type, ' '.join(args)))
  File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "./ola_rdm_get.py", line 248, in do_get
    self.GetOrSet(PidStore.RDM_GET, line)
  File "./ola_rdm_get.py", line 318, in GetOrSet
    args, help_string = pid.GetRequestDescription(request_type)
  File "/usr/lib/python2.7/dist-packages/ola/PidStore.py", line 204, in GetRequestDescription
    return group.GetDescription()
  File "/usr/lib/python2.7/dist-packages/ola/PidStore.py", line 849, in GetDescription
    output.append(atom.GetDescription(indent=2))
  File "/usr/lib/python2.7/dist-packages/ola/PidStore.py", line 366, in GetDescription
    return ('%s%s: <%s> %s' % (indent, self.name, self._GetAllowedRanges(),
  File "/usr/lib/python2.7/dist-packages/ola/PidStore.py", line 393, in _GetAllowedRanges
    (self._AccountForMultiplier(range.min),
AttributeError: 'UInt16' object has no attribute '_AccountForMultiplier'
```

**Comment by rmull** [comment]
Quick update - if I add an extra argument formatted in base-10, I instead get the following:
'''
$ ./ola_rdm_get.py -u 1 -d 2 --uid 3638:12000001 parameter_description 32999
Can't send GET PARAMETER_DESCRIPTION to non root sub devices
'''
Hexadecimal and non-existent args trigger the traceback.

**Comment by nomis52** [comment]
Ah I see the problem, b1b6606f46e47e0879b03a1155d4566ded4a3076 renamed the _AccountForMultiplier() method but didn't fix all the callees. 

@peternewman  do you mind fixing this one.

**Comment by peternewman** [comment]
Sorry, my sloppy coding, now sorted and will be in 0.9.8 (when I cherry pick shortly).
