### ISSUE TITLE
ola/OlaClientTester doesn't complete when a usbdmx device is plugged in

### ISSUE THREAD

**Issue by peternewman** [OpenLightingProject/ola#958]
./ola/OlaClientTester -l 4
olad/OlaDaemon.cpp:121: Using configs in /home/peter/.ola
common/thread/Mutex.cpp:115: Waiting with pthread
common/thread/Thread.cpp:192: Thread pref-saver, policy SCHED_OTHER, priority 0
common/thread/Mutex.cpp:117: Waited
olad/OlaServer.cpp:194: Server UID is 7a70:5a00000a
olad/OlaServer.cpp:206: Server instance name is Ola Server 2
common/thread/Mutex.cpp:115: Waiting with pthread
common/thread/Thread.cpp:192: Thread bonjour, policy SCHED_OTHER, priority 0
common/thread/Mutex.cpp:117: Waited
olad/OlaServer.cpp:481: Updated PID definitions.
olad/OlaServer.cpp:489: PID store is at 0x9c65348
common/thread/Mutex.cpp:115: Waiting with pthread
common/thread/Thread.cpp:192: Thread , policy SCHED_OTHER, priority 0
common/thread/Mutex.cpp:117: Waited
common/thread/Mutex.cpp:115: Waiting with pthread
olad/PluginManager.cpp:73: Skipping ArtNet because it was disabled
olad/PluginManager.cpp:73: Skipping ESP Net because it was disabled
olad/PluginManager.cpp:73: Skipping KarateLight because it was disabled
olad/PluginManager.cpp:73: Skipping KiNET because it was disabled
olad/PluginManager.cpp:73: Skipping Milford Instruments because it was disabled
olad/PluginManager.cpp:73: Skipping Renard because it was disabled
olad/PluginManager.cpp:73: Skipping SandNet because it was disabled
olad/PluginManager.cpp:73: Skipping ShowNet because it was disabled
olad/PluginManager.cpp:73: Skipping StageProfi because it was disabled
olad/PluginManager.cpp:73: Skipping Pathport because it was disabled
olad/PluginManager.cpp:73: Skipping UART native DMX because it was disabled
olad/PluginManager.cpp:195: Trying to start Dummy
olad/plugin_api/DeviceManager.cpp:105: Installed device: Dummy Device:1-1
olad/plugin_api/PortManager.cpp:119: Patched 1-1-O-0 to universe 0
olad/PluginManager.cpp:200: Started Dummy
olad/PluginManager.cpp:195: Trying to start Serial USB
common/thread/Mutex.cpp:115: Waiting with pthread
common/thread/Thread.cpp:192: Thread , policy SCHED_OTHER, priority 0
common/thread/Mutex.cpp:117: Waited
common/thread/Mutex.cpp:115: Waiting with pthread
common/thread/Mutex.cpp:117: Waited
olad/PluginManager.cpp:200: Started Serial USB
olad/PluginManager.cpp:195: Trying to start Enttec Open DMX
common/io/IOUtils.cpp:39: open(/dev/dmx0): No such file or directory
plugins/opendmx/OpenDmxPlugin.cpp:80: Could not open /dev/dmx0 No such file or directory
olad/PluginManager.cpp:200: Started Enttec Open DMX
olad/PluginManager.cpp:195: Trying to start E1.31 (sACN)
olad/plugin_api/DeviceManager.cpp:105: Installed device: E1.31 (DMX over ACN) [10.0.0.90]:11-1
olad/PluginManager.cpp:200: Started E1.31 (sACN)
olad/PluginManager.cpp:195: Trying to start USB
plugins/usbdmx/AsyncPluginImpl.cpp:95: Async
common/thread/Mutex.cpp:115: Waiting with pthread
common/thread/Thread.cpp:192: Thread , policy SCHED_OTHER, priority 0
common/thread/Mutex.cpp:117: Waited
olad/PluginManager.cpp:200: Started USB
olad/PluginManager.cpp:188: Not enabling FTDI USB DMX because it conflicts with Serial USB which is already running
olad/PluginManager.cpp:195: Trying to start OSC
plugins/osc/OSCDevice.cpp:88: No targets specified for OSC Output port 0
plugins/osc/OSCDevice.cpp:88: No targets specified for OSC Output port 3
plugins/osc/OSCDevice.cpp:88: No targets specified for OSC Output port 4
olad/plugin_api/DeviceManager.cpp:105: Installed device: OSC Device:14-1
olad/plugin_api/PortManager.cpp:119: Patched 14-1-I-0 to universe 0
olad/plugin_api/PortManager.cpp:119: Patched 14-1-I-1 to universe 99
olad/PluginManager.cpp:200: Started OSC
olad/PluginManager.cpp:195: Trying to start SPI
olad/PluginManager.cpp:200: Started SPI
olad/PluginManager.cpp:195: Trying to start Open Pixel Control
olad/PluginManager.cpp:200: Started Open Pixel Control
olad/PluginManager.cpp:195: Trying to start GPIO
olad/PluginManager.cpp:200: Started GPIO
common/thread/Mutex.cpp:117: Waited
plugins/usbdmx/JaRuleFactory.cpp:52: Found a new Ja Rule device
plugins/usbdmx/JaRuleFactory.cpp:55: Adding widget
./plugins/usbdmx/WidgetFactory.h:172: Adding Widget
libs/usb/LibUsbThread.cpp:51: -- Starting libusb thread
common/thread/Mutex.cpp:115: Waiting with pthread
olad/OlaDaemon.cpp:148: Shutting down
common/thread/Thread.cpp:192: Thread , policy SCHED_OTHER, priority 0
libs/usb/LibUsbThread.cpp:34: ----libusb event thread is running
libs/usb/LibUsbThread.cpp:42: Pre handle
common/thread/Mutex.cpp:117: Waited
libs/usb/LibUsbThread.cpp:44: Post handle
libs/usb/LibUsbThread.cpp:42: Pre handle
libs/usb/LibUsbThread.cpp:44: Post handle
libs/usb/LibUsbThread.cpp:42: Pre handle
libs/usb/LibUsbThread.cpp:44: Post handle
libs/usb/LibUsbThread.cpp:42: Pre handle
libs/usb/LibUsbThread.cpp:44: Post handle
libs/usb/LibUsbThread.cpp:42: Pre handle
libs/usb/LibUsbThread.cpp:44: Post handle
libs/usb/LibUsbThread.cpp:42: Pre handle
libs/usb/LibUsbThread.cpp:44: Post handle
libs/usb/LibUsbThread.cpp:42: Pre handle
libs/usb/LibUsbThread.cpp:44: Post handle
libs/usb/LibUsbThread.cpp:42: Pre handle
libs/usb/JaRuleWidget.cpp:250: Found Ja Rule port at 1
libs/usb/JaRuleWidget.cpp:265: Found JaRule device : 3800:00162400
libs/usb/JaRuleWidget.cpp:89: InternalInit: 1
libs/usb/JaRuleWidget.cpp:97: Init: 1
./plugins/usbdmx/WidgetFactory.h:177: Widget initialised
./plugins/usbdmx/SyncronizedWidgetObserver.h:59: Adding NewWidget
plugins/usbdmx/SyncronizedWidgetObserver.cpp:41: Dispatching
plugins/usbdmx/SyncronizedWidgetObserver.cpp:46: Future
plugins/usbdmx/SyncronizedWidgetObserver.cpp:47: SS: 0x9bee8f8
plugins/usbdmx/SyncronizedWidgetObserver.cpp:49: Future Exec
plugins/usbdmx/SyncronizedWidgetObserver.cpp:54: Post Future Exec
./include/ola/thread/FuturePrivate.h:64: Get Future
./include/ola/thread/FuturePrivate.h:66: Post locker
./include/ola/thread/FuturePrivate.h:71: Wait
common/thread/Mutex.cpp:115: Waiting with pthread
libs/usb/LibUsbThread.cpp:44: Post handle
libs/usb/LibUsbThread.cpp:42: Pre handle
^C

**Comment by peternewman** [comment]
#0  0xb7fe2430 in __kernel_vsyscall ()
#1  0xb78af636 in poll () from /lib/tls/i686/cmov/libc.so.6
#2  0xb75dfcd0 in ?? () from /lib/libusb-1.0.so.0
#3  0xb75e0511 in libusb_handle_events_timeout () from /lib/libusb-1.0.so.0
#4  0xb75e05b2 in libusb_handle_events () from /lib/libusb-1.0.so.0
#5  0xb7e07c2d in ola::usb::LibUsbThread::Run (this=0x80bc118) at libs/usb/LibUsbThread.cpp:43
#6  0xb7cdcdfe in ola::thread::Thread::_InternalRun (this=0x80bc118) at common/thread/Thread.cpp:199
#7  0xb7cdd0ad in StartThread (d=0x80bc118) at common/thread/Thread.cpp:47
#8  0xb794f96e in start_thread () from /lib/tls/i686/cmov/libpthread.so.0
#9  0xb78bd51e in clone () from /lib/tls/i686/cmov/libc.so.6


#0  0xb7fe2430 in __kernel_vsyscall ()
#1  0xb7954015 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/tls/i686/cmov/libpthread.so.0
#2  0xb7cda8ee in ola::thread::ConditionVariable::Wait (this=0x805e1f0, mutex=0x805e1d8) at common/thread/Mutex.cpp:116
#3  0xb7df4b0f in ola::thread::FutureImpl<bool>::Get (this=0x805e1d8) at ./include/ola/thread/FuturePrivate.h:72
#4  0xb7df5dd4 in ola::thread::Future<bool>::Get (this=0x8092b18, widget=0x8073188) at ./include/ola/thread/Future.h:59
#5  ola::plugin::usbdmx::SyncronizedWidgetObserver::DispatchNewWidget<ola::usb::JaRuleWidget> (this=0x8092b18, widget=0x8073188)
    at plugins/usbdmx/SyncronizedWidgetObserver.cpp:55
#6  0xb7de6e2c in ola::plugin::usbdmx::SyncronizedWidgetObserver::NewWidget (this=0x8092b18, widget=0x8073188) at ./plugins/usbdmx/SyncronizedWidgetObserver.h:60
#7  0xb7df003d in ola::plugin::usbdmx::BaseWidgetFactory<ola::usb::JaRuleWidget>::AddWidget (this=0x808ab80, observer=0x8092b18, widget=0x8073188)
    at ./plugins/usbdmx/WidgetFactory.h:179
#8  0xb7defd2a in ola::plugin::usbdmx::JaRuleFactory::DeviceAdded (this=0x808ab80, observer=0x8092b18, usb_device=0x8073550, descriptor=...)
    at plugins/usbdmx/JaRuleFactory.cpp:56
#9  0xb7de3095 in ola::plugin::usbdmx::AsyncPluginImpl::SetupUSBDevice (this=0x8092b00, usb_device=0x8073550) at plugins/usbdmx/AsyncPluginImpl.cpp:262
#10 0xb7de34af in ola::plugin::usbdmx::AsyncPluginImpl::DeviceEvent (this=0x8092b00, event=ola::usb::HotplugAgent::DEVICE_ADDED, device=0x8073550)
    at plugins/usbdmx/AsyncPluginImpl.cpp:208
#11 0xb7de4b7a in ola::MethodCallback0_2<ola::plugin::usbdmx::AsyncPluginImpl, ola::Callback2<void, ola::usb::HotplugAgent::EventType, libusb_device*>, void, ola::usb::HotplugAgent::EventType, libusb_device*>::DoRun (this=0x80a77f0, arg0=ola::usb::HotplugAgent::DEVICE_ADDED, arg1=0x8073550) at ./include/ola/Callback.h:2006
#12 0xb7de4b3f in ola::Callback2<void, ola::usb::HotplugAgent::EventType, libusb_device*>::Run (this=0x80a77f0, arg0=ola::usb::HotplugAgent::DEVICE_ADDED,
    arg1=0x8073550) at ./include/ola/Callback.h:1898
#13 0xb7e00dff in ola::usb::HotplugAgent::ScanUSBDevices (this=0x80c15f8) at libs/usb/HotplugAgent.cpp:235
#14 0xb7e01a3c in ola::MethodCallback0_0<ola::usb::HotplugAgent, ola::Callback0<bool>, bool>::DoRun (this=0x1) at ./include/ola/Callback.h:232
#15 0xb7e01a11 in ola::Callback0<bool>::Run (this=0x8097bb8) at ./include/ola/Callback.h:132
#16 0xb7cdaa61 in ola::thread::PeriodicThread::Run (this=0x8086608) at common/thread/PeriodicThread.cpp:57
#17 0xb7cdcdfe in ola::thread::Thread::_InternalRun (this=0x8086608) at common/thread/Thread.cpp:199
#18 0xb7cdd0ad in StartThread (d=0x8086608) at common/thread/Thread.cpp:47
#19 0xb794f96e in start_thread () from /lib/tls/i686/cmov/libpthread.so.0
#20 0xb78bd51e in clone () from /lib/tls/i686/cmov/libc.so.6


#0  0xb7fe2430 in __kernel_vsyscall ()
#1  0xb78b6421 in select () from /lib/tls/i686/cmov/libc.so.6
#2  0xb7c57566 in ola::io::SelectPoller::Poll (this=0x80732b8, timeout_manager=0x80c2368, poll_interval=...) at common/io/SelectPoller.cpp:241
#3  0xb7c51202 in ola::io::SelectServer::CheckForEvents (this=0x808847c, poll_interval=...) at common/io/SelectServer.cpp:354
#4  0xb7c5298a in ola::io::SelectServer::Run (this=0x808847c) at common/io/SelectServer.cpp:136
#5  0xb7b26d95 in ola::BonjourDiscoveryAgent::RunThread (this=0x8088478) at olad/BonjourDiscoveryAgent.cpp:176
#6  0xb7b2874c in ola::MethodCallback0_0<ola::BonjourDiscoveryAgent, ola::SingleUseCallback0<void>, void>::DoRun (this=0xb6d12ed4) at ./include/ola/Callback.h:232
#7  0xb7b28602 in ola::SingleUseCallback0<void>::Run (this=0x8073eb8) at ./include/ola/Callback.h:161
#8  0xb7b28668 in ola::thread::CallbackThread::Run (this=0x807df78) at ./include/ola/thread/CallbackThread.h:54
#9  0xb7cdcdfe in ola::thread::Thread::_InternalRun (this=0x807df78) at common/thread/Thread.cpp:199
#10 0xb7cdd0ad in StartThread (d=0x807df78) at common/thread/Thread.cpp:47
#11 0xb794f96e in start_thread () from /lib/tls/i686/cmov/libpthread.so.0
#12 0xb78bd51e in clone () from /lib/tls/i686/cmov/libc.so.6


#0  0xb7fe2430 in __kernel_vsyscall ()
#1  0xb78b6421 in select () from /lib/tls/i686/cmov/libc.so.6
#2  0xb7c57566 in ola::io::SelectPoller::Poll (this=0x805bb88, timeout_manager=0x8055798, poll_interval=...) at common/io/SelectPoller.cpp:241
#3  0xb7c51202 in ola::io::SelectServer::CheckForEvents (this=0x805645c, poll_interval=...) at common/io/SelectServer.cpp:354
#4  0xb7c5298a in ola::io::SelectServer::Run (this=0x805645c) at common/io/SelectServer.cpp:136
#5  0xb7795a10 in ola::FilePreferenceSaverThread::Run (this=0x80563f8) at olad/plugin_api/Preferences.cpp:365
#6  0xb7cdcdfe in ola::thread::Thread::_InternalRun (this=0x80563f8) at common/thread/Thread.cpp:199
#7  0xb7cdd0ad in StartThread (d=0x80563f8) at common/thread/Thread.cpp:47
#8  0xb794f96e in start_thread () from /lib/tls/i686/cmov/libpthread.so.0
#9  0xb78bd51e in clone () from /lib/tls/i686/cmov/libc.so.6


#0  0xb7fe2430 in __kernel_vsyscall ()
#1  0xb7950b5d in pthread_join () from /lib/tls/i686/cmov/libpthread.so.0
#2  0xb7cdc16f in ola::thread::Thread::Join (this=0x8086608, ptr=0x0) at common/thread/Thread.cpp:158
#3  0xb7cdabb9 in ola::thread::PeriodicThread::Stop (this=0x8086608) at common/thread/PeriodicThread.cpp:49
#4  0xb7e00ebc in ola::usb::HotplugAgent::HaltNotifications (this=0x80c15f8) at libs/usb/HotplugAgent.cpp:129
#5  0xb7de194a in ola::plugin::usbdmx::AsyncPluginImpl::Stop (this=0x8092b00) at plugins/usbdmx/AsyncPluginImpl.cpp:138
#6  0xb7deb1b8 in ola::plugin::usbdmx::UsbDmxPlugin::StopHook (this=0x80711d8) at plugins/usbdmx/UsbDmxPlugin.cpp:83
#7  0xb778ff4a in ola::Plugin::Stop (this=0x80711d8) at olad/plugin_api/Plugin.cpp:104
#8  0xb7b251a3 in ola::PluginManager::UnloadAll (this=0x807ee10) at olad/PluginManager.cpp:90
#9  0xb7b5e54f in ola::OlaServer::StopPlugins (this=0x805d7e8) at olad/OlaServer.cpp:448
#10 0xb7b5e7a1 in ~OlaServer (this=0x805d7e8, __in_chrg=<value optimised out>) at olad/OlaServer.cpp:131
#11 0xb7b62bf9 in std::auto_ptr<ola::OlaServer>::reset (this=0x805b200) at /usr/include/c++/4.4/backward/auto_ptr.h:242
#12 ola::OlaDaemon::Shutdown (this=0x805b200) at olad/OlaDaemon.cpp:149
#13 0xb7b630d5 in ~OlaDaemon (this=0x805b200, __in_chrg=<value optimised out>) at olad/OlaDaemon.cpp:99
#14 0x080501b9 in ~auto_ptr (this=0x8057cf8, __in_chrg=<value optimised out>) at /usr/include/c++/4.4/backward/auto_ptr.h:168
#15 ~OlaServerThread (this=0x8057cf8, __in_chrg=<value optimised out>) at ola/StreamingClientTest.cpp:72
#16 0xb7fa67b9 in CppUnit::TestCaseMethodFunctor::operator()() const () from /usr/lib/libcppunit-1.12.so.1
#17 0xb7f99528 in CppUnit::DefaultProtector::protect(CppUnit::Functor const&, CppUnit::ProtectorContext const&) () from /usr/lib/libcppunit-1.12.so.1
#18 0xb7fa2c93 in CppUnit::ProtectorChain::ProtectFunctor::operator()() const () from /usr/lib/libcppunit-1.12.so.1
#19 0xb7fa2755 in CppUnit::ProtectorChain::protect(CppUnit::Functor const&, CppUnit::ProtectorContext const&) () from /usr/lib/libcppunit-1.12.so.1
#20 0xb7fadb67 in CppUnit::TestResult::protect(CppUnit::Functor const&, CppUnit::Test*, std::string const&) () from /usr/lib/libcppunit-1.12.so.1
#21 0xb7fa65e2 in CppUnit::TestCase::run(CppUnit::TestResult*) () from /usr/lib/libcppunit-1.12.so.1
#22 0xb7fa6d56 in CppUnit::TestComposite::doRunChildTests(CppUnit::TestResult*) () from /usr/lib/libcppunit-1.12.so.1
#23 0xb7fa6c7a in CppUnit::TestComposite::run(CppUnit::TestResult*) () from /usr/lib/libcppunit-1.12.so.1
#24 0xb7fa6d56 in CppUnit::TestComposite::doRunChildTests(CppUnit::TestResult*) () from /usr/lib/libcppunit-1.12.so.1
#25 0xb7fa6c7a in CppUnit::TestComposite::run(CppUnit::TestResult*) () from /usr/lib/libcppunit-1.12.so.1
#26 0xb7fafccc in CppUnit::TestRunner::WrappingSuite::run(CppUnit::TestResult*) () from /usr/lib/libcppunit-1.12.so.1
#27 0xb7fad70a in CppUnit::TestResult::runTest(CppUnit::Test*) () from /usr/lib/libcppunit-1.12.so.1
#28 0xb7fafaf0 in CppUnit::TestRunner::run(CppUnit::TestResult&, std::string const&) () from /usr/lib/libcppunit-1.12.so.1
#29 0xb7fb2d2b in CppUnit::TextTestRunner::run(CppUnit::TestResult&, std::string const&) () from /usr/lib/libcppunit-1.12.so.1
#30 0xb7fb2da2 in CppUnit::TextTestRunner::run(std::string, bool, bool, bool) () from /usr/lib/libcppunit-1.12.so.1
#31 0x08051283 in main (argc=1, argv=0xbffff714) at common/testing/GenericTester.cpp:75
